# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: 'Beman pre-commit check'
on:
  workflow_call:
jobs:
  pre-commit-push:
    name: Pre-Commit check on Push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.13

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pip install pre-commit && pre-commit run --all-files

  pre-commit-pr:
    name: Pre-Commit check on PR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}

    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

        # pull_request_target checkout the base of the repo
        # We need to checkout the actual pr to lint the changes.
      - name: Checkout pr
        run: gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.13

      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        id: run-pre-commit
        run: pip install pre-commit && pre-commit run --all-files

        # Review dog posts the suggested change from pre-commit to the pr.
      - name: suggester / pre-commit
        uses: reviewdog/action-suggester@c387862ad6765a9729f2b40ee4d8b5769f2145c7 # v1.26.1
        if: ${{ failure() && steps.run-pre-commit.conclusion == 'failure' }}
        with:
          tool_name: pre-commit
          level: warning
          reviewdog_flags: "-fail-level=error"
